FROM ubuntu:22.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y curl \
    && apt-get install -y python3 python3-dev python3-distutils 

## Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py

## Install dependencies
# No additional dependencies needed (uses only json)

COPY preprocess_computational_biology_lab.py preprocess_computational_biology_lab.py
