FROM ubuntu:22.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y python3 python3-dev python3-distutils \
    && rm -rf /var/lib/apt/lists/*

COPY preprocess_bank_qna.py preprocess_bank_qna.py
