FROM ubuntu:22.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y curl python3 python3-dev python3-distutils \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py && rm get-pip.py

RUN pip3 install --no-cache-dir datasets

COPY preprocess_fin_phrasebank.py preprocess_fin_phrasebank.py
