FROM ubuntu:20.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get upgrade && apt-get update \
    && apt-get install -y python3 python3-pip

# Install CPU-only version of PyTorch
RUN pip3 install torch --index-url https://download.pytorch.org/whl/cpu

RUN pip3 install torch transformers peft bitsandbytes pathlib

ENV CUDA_VISIBLE_DEVICES=""

COPY load_base_model.py load_base_model.py